name: Run LAMP ECS Task in Environment
description: Run an existing task in the LAMP ECS Cluster

inputs:
  role-to-assume:
    description: IAM role
    required: true
  aws-region:
    description: AWS region to use
    required: true
    default: us-east-1
  environment:
    description: LAMP environment
    required: true
  task_name:
    description: name of the task to run in kebab case
    required: true

runs:
  using: composite
  steps:
    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
    - name: Run ECS Task
      id: run-ecs
      run: ${{ github.action_path }}/run_task.sh
      shell: bash
      env:
        AWS_REGION: ${{ inputs.aws-region }}
        TASK_NAME: ${{ inputs.task_name }}
        ENVIRONMENT: ${{ inputs.environment }}
