version: '3'

services:

  rail_pm_rds:
    container_name: ${RPM_DB_HOST}
    image: postgres:14.4
    env_file: .env
    shm_size: '2gb'
    environment:
      POSTGRES_DB: ${RPM_DB_NAME}
      POSTGRES_PASSWORD: ${RPM_DB_PASSWORD}
    ports:
      - "${RPM_DB_PORT}:5432"
    command: ["postgres", "-c", "log_statement=all"]

  metadata_rds:
    container_name: ${MD_DB_HOST}
    image: postgres:15
    env_file: .env
    shm_size: '2gb'
    environment:
      POSTGRES_DB: ${MD_DB_NAME}
      POSTGRES_PASSWORD: ${MD_DB_PASSWORD}
    ports:
      - "${MD_DB_PORT}:5432"
    command: ["postgres", "-c", "log_statement=all"]

  performance_manager:
    container_name: performance_manager
    env_file: .env
    build:
      context: ./python_src
    depends_on:
      - rail_pm_rds
      - metadata_rds
    working_dir: /lamp
    volumes:
      - ~/.aws:/root/.aws:ro  # map credentials to be used by boto3, read-only
    command: ["poetry", "run", "performance_manager"]

  seed_metadata:
    container_name: seed_metadata
    env_file: .env
    build:
      context: ./python_src
    depends_on:
      - rail_pm_rds
      - metadata_rds
    working_dir: /lamp
    volumes:
      # map credentials to be used by boto3, read-only
      - ~/.aws:/root/.aws:ro
      # add in filepath json that will be the default seed file path
      - ./python_src/tests/test_files/staging_dec_10.json:/seed_paths.json
    # entrypoint passes in seed file thats added as a volume. if you want to use a different
    # filepath run
    # docker-compose run -v /path/to/files.json:/seed.json seed_metadata --seed-file /seed.json
    entrypoint:
      [
        "poetry",
        "run",
        "seed_metadata",
        "--clear-static",
        "--clear-rt",
        "--seed-file",
        "/seed_paths.json"
      ]
