version: '3'

services:

  local_rds:
    container_name: local_rds
    image: postgres:14.4
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all" ]

  performance_manager:
    container_name: performance_manager
    env_file: .env
    build:
      context: ./python_src
      dockerfile: performance_manager.dockerfile
    depends_on:
      - local_rds
    working_dir: /python_src
    volumes:
      - ~/.aws:/root/.aws:ro # map credentials to be used by boto3, read-only

  ingestion:
    container_name: ingestion
    env_file: .env
    build:
      context: ./python_src 
      dockerfile: ingestion.dockerfile
    depends_on:
      - local_rds
    working_dir: /python_src
    volumes:
      - ~/.aws:/root/.aws:ro # map credentials to be used by boto3, read-only
