name: Determine Tests To Run
description: 'Deduce which tests need to be run by looking at what files have changed'
runs:
  using: 'composite'
  steps:
    - name: Run Script and Output
      shell: bash
      run: |
        ${{ github.action_path }}/determine_tests.sh
        echo "TEST_INGESTION=$TEST_INGESTION" >> $GITHUB_ENV
        echo "TEST_AWS=$TEST_AWS" >> $GITHUB_ENV
        echo "TEST_PERFORMANCE_MANAGER=$TEST_PM" >> $GITHUB_ENV
        echo "TEST_POSTGRES=$TEST_POSTGRES" >> $GITHUB_ENV
