name: Deploy To Environment
description: Build docker image and deploy it for each data pipeline.
inputs:
  aws-role-arn:
    description: AWS_ROLE_ARN
    required: true
  docker-repo:
    description: ECR Docker repo to push to
    required: true
  env-name:
    description: One of 'prod', 'staging', or 'dev'
    required: true
  slack-webhook-url:
    description: Slack URL to post to
    required: true

runs:
  using: 'composite'
  steps:
    - uses: mbta/actions/build-push-ecr@v2
      id: build-push
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        docker-repo: ${{ inputs.docker-repo }}
        dockerfile-path: ./python_src/
    - uses: mbta/actions/deploy-ecs@v2
      id: deploy-ingestion
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        ecs-cluster: lamp
        ecs-service: lamp-ingestion-${{ inputs.env-name }}
        docker-tag: ${{ steps.build-push.outputs.docker-tag }}
    - uses: mbta/actions/deploy-ecs@v2
      id: deploy-performance-manager
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        ecs-cluster: lamp
        ecs-service: lamp-performance-manager-${{ inputs.env-name }}
        docker-tag: ${{ steps.build-push.outputs.docker-tag }}
    - uses: mbta/actions/notify-slack-deploy@v1
      if: ${{ !cancelled() }}
      with:
        webhook-url: ${{ inputs.slack-webhook-url }}
        job-status: ${{ job.status }}
