name: Lambda Deploy
description: Deploys new Lambda function code
inputs:
  aws-access-key-id:
    description: AWS access key
    required: true
  aws-secret-access-key:
    description: AWS secret key
    required: true
  dry-run:
    description: >-
      If truthy, the deploy will be a dry run, or will not be attempted at all
      if `aws-access-key-id` is blank (instead of erroring)
    required: false
    default: ""
  environment:
    description: Name of the environment to deploy to (dev/prod)
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/poetry_deps
      with:
        poetry-dir: py_gtfs_rt_ingestion

    - name: Create build folder
      working-directory: py_gtfs_rt_ingestion
      run: |
        # build the ingestion modules and install its dependencies to package
        poetry build
        poetry run pip install --upgrade -t package dist/*.whl
        # add the batch and ingest scripts to the package
        cp -v batch_files.py package/batch_files.py
        cp -v ingest.py package/ingest.py
      shell: bash

    - name: Build Home Rolled psycopg with libpq
      working-directory: .
      run: |
        sudo apt update
        sudo apt -y install libssl-dev
        # download and untar postgres 14.5 source code
        wget https://ftp.postgresql.org/pub/source/v14.5/postgresql-14.5.tar.gz
        tar -xf postgresql-14.5.tar.gz
        # download and untar psycopg 2.9.3 source code
        wget https://files.pythonhosted.org/packages/d1/1e/b450599a27b1809bccbd4e369f397cb18dc56b875778d961f9ae180b54b7/psycopg2-2.9.3.tar.gz
        tar -xf psycopg2-2.9.3.tar.gz
        # configure and build postgresql 14.5 from soruce
        postgres_src="/home/runner/work/lamp/lamp/postgresql-14.5"
        cd $postgres_src
        ./configure --prefix $postgres_src --without-readline --without-zlib --with-openssl
        make
        make install
        # configure (via sed) and build psycopg2
        cd ../psycopg2-2.9.3
        sed -i "s/^pg_config.*$/pg_config = \/home\/runner\/work\/lamp\/lamp\/postgresql-14.5\/bin\/pg_config/g" setup.cfg
        sed -i "s/^static_libpq.*$/static_libpq = 1/g" setup.cfg
        sed -i "s/^libraries.*$/libraries = ssl crypto/g" setup.cfg
        cat setup.cfg
        python setup.py build
        ls build/lib.linux-x86_64-3.9/psycopg2
      shell: bash

    - name: Install psycopg2 with libpq
      working-directory: py_gtfs_rt_ingestion
      run: |
        # remove psycopg2 and update it with our home built one
        rm -r package/psycopg2
        mv /home/runner/work/lamp/lamp/psycopg2-2.9.3/build/lib.linux-x86_64-3.9/psycopg2 package/
        # add the batch and ingest scripts to the package
        cp -v batch_files.py package/batch_files.py
        cp -v ingest.py package/ingest.py
      shell: bash

    - name: Install AWS SSL Cert
      working-directory: py_gtfs_rt_ingestion/package
      run: |
        curl https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem -o aws-cert-bundle.pem
        echo "acaf8712f8d71c05f85503c6b90fd0127e95ff0091bf094a22a650119684a08e  aws-cert-bundle.pem" | sha256sum -c -
      shell: bash

    - name: Create zip archive
      working-directory: py_gtfs_rt_ingestion/package
      run: |
        zip -r ../lamp_lambdas.zip . -x '*.pyc'
      shell: bash

    - name: Deploy Ingest Lambda
      working-directory: py_gtfs_rt_ingestion
      run: >-
        aws lambda update-function-code
        --function-name lamp-${{ inputs.environment }}-ingest
        --zip-file fileb://lamp_lambdas.zip
        ${{ inputs.dry-run && '--dry-run' || '' }}
      if: ${{ !inputs.dry-run || inputs.aws-access-key-id }}
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_REGION: us-east-1

    - name: Deploy Batch Lambda
      working-directory: py_gtfs_rt_ingestion
      run: >-
        aws lambda update-function-code
        --function-name lamp-${{ inputs.environment }}-batcher
        --zip-file fileb://lamp_lambdas.zip
        ${{ inputs.dry-run && '--dry-run' || '' }}
      if: ${{ !inputs.dry-run || inputs.aws-access-key-id }}
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_REGION: us-east-1
