name: Continuous Integration (Elixir)

on:
  push:
    branches: main
    paths:
      - 'api/**'
      - '.github/workflows/ci_elixir.yaml'
      - '.github/elixir_deps/action.yaml'
  pull_request:
    paths:
      - 'api/**'
      - '.github/workflows/ci_elixir.yaml'
      - '.github/elixir_deps/action.yaml'

defaults:
  run:
    working-directory: api 

concurrency:
  group: elixir-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Elixir Setup
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/elixir_deps

  compile:
    name: Compile
    runs-on: ubuntu-22.04
    needs: setup

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/elixir_deps

      - run: mix compile --force --warnings-as-errors

  format:
    name: Format
    runs-on: ubuntu-22.04
    needs: setup

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/elixir_deps

      - run: mix format --check-formatted

  test:
    name: Test Tasks
    runs-on: ubuntu-22.04
    needs: setup

    services:
      postgres:
        image: postgres:14.4
        ports:
          - 5432:5432
        env:
          # matches api/config/test.exs
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: performance_manager_test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/elixir_deps
      - uses: ./.github/actions/python_deps

      - run: mix test
