name: Deploy to Production Environment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          docker-repo: ${{ secrets.LAMP_DOCKER_URI }}
          env-name: prod
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK }}
