name: Deploy to Staging Environment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types: [completed]
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/deploy
        with:
          env-name: staging