name: Deploy to Production

on:
  # deploy when version tags are published
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  deploy:
    name: Deploy to Production
    concurrency:
      group: prod
    uses: ./.github/workflows/deploy-base.yaml
    with:
      environment: prod
      deploy-ingestion: true
      deploy-rail-pm: true
      deploy-bus-pm: true
      deploy-tm-ingestion: true
      deploy-tableau-publisher: true
    secrets: inherit
