name: Deploy to Staging

on:
  # deploy when ci has been completed on main (should occur after new commits are added to main
  # directly or via pull request)
  workflow_run:
    workflows: ["Continuous Integration (Python)"]
    types: [completed]
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Staging
    concurrency:
      group: staging
    uses: ./.github/workflows/deploy-base.yaml
    with:
      environment: staging
      deploy-ingestion: true
      deploy-rail-pm: true
      deploy-bus-pm: true
      deploy-tm-ingestion: true
      deploy-tableau-publisher: true
    secrets: inherit
