name: Deploy to Staging Environment

on:
  workflow_run:
    workflows: ["Continuous Integration (Python)"]
    types: [completed]
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: mbta/actions/deploy-ecs@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          docker-repo: ${{ secrets.LAMP_DOCKER_URI }}
          env-name: staging
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK }}
