name: Ingestion CI

on:
  push:
    branches:
      - main
    paths:
      - 'py_gtfs_rt_ingestion/**'
  pull_request:
    paths:
      - 'py_gtfs_rt_ingestion/**'

defaults:
  run:
    shell: bash
    working-directory: py_gtfs_rt_ingestion

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/poetry_deps
        with:
          poetry-dir: py_gtfs_rt_ingestion

  format:
    name: Format
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/poetry_deps
        with:
          poetry-dir: py_gtfs_rt_ingestion
      - run: poetry run black . --check

  typing:
    name: Type Check
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/poetry_deps
        with:
          poetry-dir: py_gtfs_rt_ingestion
      - run: poetry run mypy .

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/poetry_deps
        with:
          poetry-dir: py_gtfs_rt_ingestion
      - run: poetry run pylint *.py lib/ tests/
