name: Lambda CI

on:
  push:
    branches: main
    paths:
      - 'py_gtfs_rt_ingestion/**'
  pull_request:
    paths:
      - 'py_gtfs_rt_ingestion/**'

defaults:
  run:
    shell: bash
    working-directory: py_gtfs_rt_ingestion

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/poetry_deps
        with:
          poetry-dir: py_gtfs_rt_ingestion

  deploy:
    name: Dry-Deploy
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/lambda_deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          dry-run: "true"
          environment: dev

  format:
    name: Format
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/poetry_deps
        with:
          poetry-dir: py_gtfs_rt_ingestion
      - run: poetry run black . --check

  typing:
    name: Type Check
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/poetry_deps
        with:
          poetry-dir: py_gtfs_rt_ingestion
      - run: poetry run mypy .

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/poetry_deps
        with:
          poetry-dir: py_gtfs_rt_ingestion
      - run: poetry run pylint *.py py_gtfs_rt_ingestion/ tests/

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/poetry_deps
        with:
          poetry-dir: py_gtfs_rt_ingestion
      - run: poetry run pytest

 
