name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        options:
          - dev
          - staging
          - prod
      deploy-ingestion:
        description: Deploy Ingestion
        default: false
        type: boolean
      deploy-rail-pm:
        description: Deploy Rail Performance Manager
        default: false
        type: boolean
      deploy-tableau-publisher:
        description: Deploy Tableau Publisher (only run on Prod)
        default: false
        type: boolean

jobs:
  deploy:
    name: Deploy to Production
    concurrency:
      group: github.event.inputs.environment
    uses: ./.github/workflows/deploy-base.yaml
    with:
      env-name: github.event.inputs.environment
      deploy-ingestion: github.envent.inputs.deploy-ingestion
      deploy-rail-pm: github.envent.inputs.deploy-rail-pm
      deploy-tableau-publisher: github.envent.inputs.deploy-tableau-publisher
    secrets: inherit
