name: Run Task

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        options:
          - staging
          - prod
      task:
        description: Task
        type: choice
        options:
          - Tableau Publisher
          - Transit Master Ingestion

jobs:
  run_task:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Generate Task Name
        run: |
          if [ "${{ github.event.inputs.task }}" == "Tableau Publisher" ]; then
            echo "task_name=tableau-publisher" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.task }}" == "Transit Master Ingestion" ]; then
            echo "task_name=tm-ingestion" >> $GITHUB_ENV
          fi
      - name: Run Task Action
        uses: ./.github/actions/run_task
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          environment: ${{ inputs.environment }}
          task_name: ${{ env.task_name }}
